config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  get 'profiles/profile'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  root 'posts#index'
  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
  end

  resources :posts do
    resources :comments
  end

  get 'trend' => 'posts#trend'
  get 'foodie' => 'posts#foodie'
  get 'user' => 'users#user'

  get ':user_name', to: 'profiles#show', as: :profile

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :user_id, presence: true
  validates :image, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

acts_as_votable

  has_attached_file :image, styles: { :medium => "640x"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


  def self.highest_voted
    self.order("cached_votes_score DESC")
  end

  def self.search(search)
    where("caption LIKE ?", "%#{search}%")
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  acts_as_voter

  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = "Thanks for the love!"
      redirect_to @post
    else
      flash[:alert] = "You missed something!"
      render root_path
    end
  end

  def destroy
  @comment = @post.comments.find(params[:id])

  @comment.destroy
  flash[:success] = "Fine, Take It Back!"
  redirect_to @post
end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :owned_post, only: [:edit, :update, :destroy]


  def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to @post
  end


  def index
    @page = (params[:page] || 1).to_i
    offset = (@page - 1) * 25

    @posts = Post.order(created_at: :desc).limit(25).
    offset(offset).all

    @posts = Post.all
    if params[:search]
   @posts = Post.search(params[:search]).order("created_at DESC")
    else
      @posts = Post.all.order('created_at DESC')
    end

  end


  def trend
    @posts = Post.highest_voted
  end

  def foodie
    @posts = Post.all
  end


  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end


  def edit
    @post = Post.find(params[:id])
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def owned_post
    unless current_user == @post.user
      flash[:alert] = "Not Allowed!"
      redirect_to root_path
    end
  end

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
    @user = User.find_by(user_name: params[:user_name])
  end

  def profile

  @posts = current_user.posts

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end  

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" style="border-radius:0px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=image_tag("logo.jpg", class:"logopic") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "FEED", root_path%></li>
        <li><%= link_to "TRENDING", trend_path%></li>
        <% if user_signed_in? %>
        <li><%= link_to "PROFILE", profiles_profile_path%></li>
        <li><%= link_to "NEW POST", new_post_path%></li>
        <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete%></li>
        <% else %>
        <li><%= link_to "LOG IN", new_user_session_path %></li>
        <li><%= link_to "SIGN UP", new_user_registration_path%></li>
      </li>
      <% end %>
    </ul>
<% if current_page?('/') || current_page?('/index') %>
    <div class="col-sm-3 col-md-3 pull-right">
      <form class="navbar-form" role="search">
        <div class="input-group">
          <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Posts",class: "form-control" %>
          <div class="input-group-btn">
          <%= submit_tag "Search", class: 'btn btn-info'%>
          <% end %>
        </div>
        <% end %>
        </div>
    </div>
  </form>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="user-name">
        <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
      <% if post.comments %>
        <% post.comments.each do |comment| %>
          <div class="comment">
            <div class="user-name">
              <%= comment.user.user_name %>
            </div>
            <div class="comment-content">
              <%= comment.content %>
            </div>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
      <div class="comment-form">
        <%= form_for [post, post.comments.new] do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...' %>
          <%= f.button :submit, class: "btn-xs btn btn-success"  %>
          <%= link_to "Like", like_post_path(post), class: "btn-xs btn btn-info", method: :put %>
          <%= post.votes_for.size %>
        <% end %>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div class="user-name">
          <%= post.user.user_name %>
        </div>
        <%= post.caption %>
      </div>
      <% if post.comments %>
        <% post.comments.each do |comment| %>
          <div class="comment">
            <div class="user-name">
              <%= comment.user.user_name %>
            </div>
            <div class="comment-content">
              <%= comment.content %>
            </div>
            <% if comment.user == current_user %>
              <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } do %>
                <span>(class="glyphicon glyphicon-remove delete-comment")</span>
              <% end %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <span>(class="glyphicon glyphicon-heart-empty")</span>
      </div>
      <div class="comment-form col-sm-11">
        <%= form_for [post, post.comments.new] do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1>Make changes Below!</h1>

<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        <%= link_to "FEED", posts_path, class: "btn-xs btn btn-info" %>
      <%= link_to "Delete Post", post_path(@post), class: "btn-xs btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="log-in panel">
      <div class="panel-heading">
      <%= f.input :image, label: false %><br>
      <%= f.input :caption, label: false, input_html: { class: 'form-control' } %><br>
      <%= f.button :submit, class: "btn btn-success"  %>
    <% end %>
  </div>
</div>
</div>

app/views/posts/foodie.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <table class="table_class">

    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.user.user_name %></td>
          <td class="mini_button_blue"><%= link_to 'Details', post %></td>
          <td class="mini_button_blue"><%= link_to 'Edit', edit_post_path(post) %></td>
          <td class="mini_button_blue"><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <% if params[:search]%>
    <% if @posts.present? %>
    <h2>Ok, This is what we found!</h2>
    <%= render @posts %>
    <% else %>
    <div align="center">
    <h2>There are no posts containing<br>the term(s) <%= params[:search] %>.</h2><br>
  </div>
    <%end %>
  <% else %>
  <h3>Welcome to Foodie!</h3>
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-4 post">
      <div class="post-head">
        <div class="thumb-img"></div>
        <div class="user-name">
          <%= link_to post.user.user_name, profile_path(post.user.user_name) %> <i class="fa fa-comments fa-lg"></i> <%= post.caption %>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
      </div>
      <div class="post-bottom">
        <div class="comment-form">
            <%= link_to "Like", like_post_path(post), class: "btn-xs btn btn-info", method: :put %>
            <%= post.votes_for.size %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <%end %>
</div>

app/views/posts/new.html.erb
<div class="login-bg">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class="log-in panel">
          <div class="panel-heading">
            <h2>Create a Post</h2>
          </div>
          <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
            <div class="panel-body">
              <%= f.input :image, label: false %><br>
              <P>Add a caption!</p>
                  <p>Don't forget to tag a restaurant <br> Ex: Something nice @Dada's</p>
              <%= f.input :caption, label: false, input_html: { class: 'form-control' }%><br>
              <%= f.button :submit, "Post", class: 'btn-lg btn-success btn-block' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">


  <h1>About This Post</h1>

  <div class="posts-wrapper row">
    <div class="post">
      <div class="post-head">
        <div class="user-name">
          <% if @post.user.id == current_user.id %>
          <%= link_to "FEED", posts_path, class: "btn-xs btn btn-info" %>
          <%= link_to "Edit Post", edit_post_path(@post), class: "btn-xs btn btn-warning" %>
          <i class="fa fa-comments fa-lg"></i> <%= @post.caption %>
          <% else %>
          <%= link_to "FEED", posts_path, class: "btn-xs btn btn-info" %>
          <%= link_to @post.user.user_name, profile_path(@post.user.user_name), class: "btn-xs btn btn-success" %> <i class="fa fa-comments fa-lg"></i> <%= @post.caption %>
          <% end %>
        </div>
      </div>
      <div class="image center-block">
        <%= image_tag @post.image.url(:medium) %>
      </div>
      <div class="post-bottom">
        <% if @post.comments %>
        <% @post.comments.each do |comment| %>
        <div class="comment">
          <div class="user-name">
            <%= comment.user.user_name %>
          </div>
          <div class="comment-content">
            <%= comment.content %>
          </div>
          <% if comment.user == current_user %>
          <%= link_to "Delete Comment", post_comment_path(@post, comment),class: "btn-xs btn btn-warning", method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </div>
        <% end %>
        <% end %>
        <div class="comment-form">
          <%= form_for [@post, @post.comments.new] do |f| %>
          <%= f.text_field :content, placeholder: 'Add a comment...' %>
          <%= f.button :submit, class: "btn-xs btn btn-success"  %>
          <%= link_to "Like", like_post_path(@post), class: "btn-xs btn btn-info", method: :put %>
          <%= @post.votes_for.size %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/trend.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
  <% if params[:search]%>
    <% if @posts.present? %>
    <h2>Ok, This is what we found!</h2>
    <%= render @posts %>
    <% else %>
    <div align="center">
    <h2>There are no posts containing<br>the term(s) <%= params[:search] %>.</h2><br>
  </div>
    <%end %>
  <% else %>
  <h2>Trending at Foodie!</h2>
  <h4>Below are the most liked posts!</h4>
  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4 post">
        <div class="post-head">
          <div class="thumb-img"></div>
          <div class="user-name">
            <%= link_to post.user.user_name, profile_path(post.user.user_name) %> <i class="fa fa-comments fa-lg"></i> <%= post.caption %>
          </div>
        </div>
        <div class="image center-block">
          <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
        </div>
        <div class="post-bottom">
          <div class="comment-form">
              <%= link_to "Like", like_post_path(post), class: "btn-xs btn btn-info", method: :put %>
              <%= post.votes_for.size %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>

app/views/profiles/profile.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">

  <h1>Hello Foodie, Here Are Your Posts!</h1>

<div align="center">
  <P> You are signed in as <%=current_user.user_name%>, You can See, Edit or Delete Your Posts</p><br>
    <%= link_to "Account Settings", edit_user_registration_path, class: 'btn-lg btn-warning' %>
  </div>

   <% @posts.each do |post| %>
   <%= render 'posts/post', post: post %>
   <% end %>
</div>

app/views/profiles/show.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

 <h1><%= "#{@user.user_name}'s" + " Profile"  %></h1>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>